// <auto-generated />
using System;
using CareerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareerApi.Migrations
{
    [DbContext(typeof(CareerDbContext))]
    partial class CareerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareerApi.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Portfolio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ResumeFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ResumeStoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("CareerApi.Models.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("JobPostings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "engineering",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Keywords = "mechanical design cfd turbine blade hydrodynamics solidworks ansys",
                            Location = "Roorkee, Uttarakhand",
                            PostedDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "B.Tech / M.Tech in Mechanical Engineering with 5+ years experience||Proficiency in SolidWorks, ANSYS, and CFD simulation tools||Experience in fluid-structure interaction (FSI) analysis preferred||Knowledge of hydropower, marine, or wind turbine design is a plus||Strong technical writing and cross-functional communication skills",
                            Responsibilities = "Design turbine blade profiles and housing geometries for optimal hydrodynamic performance||Conduct CFD simulations (ANSYS Fluent, OpenFOAM) and FEA stress analysis||Oversee prototyping, field testing, and design iteration cycles||Collaborate with IIT Roorkee on hydrodynamic validation studies||Prepare technical documentation for CEA and MNRE submissions",
                            Summary = "Lead the design and optimization of hydrokinetic turbine blades, housings, and modular array structures using CFD and FEA tools.",
                            Title = "Senior Mechanical Design Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Department = "engineering",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Keywords = "electrical power electronics generator inverter grid scada plc",
                            Location = "Roorkee, Uttarakhand",
                            PostedDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "B.Tech / M.Tech in Electrical Engineering with 3+ years experience||Experience with power electronics, inverters, and grid-tied systems||Proficiency in PLC programming and SCADA platforms (Ignition, WinCC)||Knowledge of IEEE 1547, CEA grid standards, and energy metering||Willingness to travel to remote project sites",
                            Responsibilities = "Design low-voltage generator and power conversion systems (50 kW - 1 MW)||Develop grid synchronization, protection, and metering solutions||Build SCADA and remote monitoring architectures for field deployments||Ensure compliance with CEA grid codes and state DISCOM requirements||Support commissioning and troubleshooting at project sites",
                            Summary = "Design and integrate generator systems, power electronics, grid interfaces, and SCADA monitoring for SHKT installations.",
                            Title = "Electrical Systems Engineer"
                        },
                        new
                        {
                            Id = 3,
                            Department = "engineering",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Keywords = "civil structural foundation anchor mooring waterway construction",
                            Location = "Roorkee / Field Sites",
                            PostedDate = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "B.Tech / M.Tech in Civil Engineering with 3+ years experience||Experience in water resource or marine structure design||Proficiency in STAAD.Pro, AutoCAD, and site surveying tools||Knowledge of hydrology, soil mechanics, and fluid forces||Field-ready - comfortable working at remote river and canal sites",
                            Responsibilities = "Design turbine mounting, anchoring, and mooring structures||Analyze hydrological and geotechnical site conditions||Prepare BOQ, tender documents, and construction drawings||Oversee on-site civil works and installation supervision||Ensure structural safety under flood and debris conditions",
                            Summary = "Design anchoring, mooring, and foundation systems for turbine deployment in rivers, canals, and discharge channels.",
                            Title = "Civil & Structural Engineer"
                        },
                        new
                        {
                            Id = 4,
                            Department = "operations",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Keywords = "project manager site execution commissioning hydro renewable energy",
                            Location = "Pan-India / International",
                            PostedDate = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "B.Tech in Engineering with 6+ years in renewable energy project management||Proven track record of executing hydro, solar, or wind projects||PMP or equivalent project management certification preferred||Strong vendor management and government liaison skills||Willingness to relocate and travel extensively across India and abroad",
                            Responsibilities = "Manage project timelines, budgets, and stakeholder coordination||Oversee site surveys, civil works, and turbine installation||Coordinate with DISCOMs, state nodal agencies, and local authorities||Ensure HSE compliance and quality assurance at all project stages||Prepare progress reports and milestone documentation for clients",
                            Summary = "Lead end-to-end project execution from site survey and civil works to turbine commissioning and handover.",
                            Title = "Project Manager — Site Execution"
                        },
                        new
                        {
                            Id = 5,
                            Department = "operations",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Keywords = "o&m maintenance technician field service turbine repair",
                            Location = "Pan-India",
                            PostedDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "Diploma / ITI in Electrical or Mechanical with 2+ years field experience||Experience in hydro, solar, or industrial maintenance preferred||Basic electrical troubleshooting and mechanical repair skills||Comfortable working in outdoor, remote, and water-adjacent environments||Valid driver's license and willingness to travel extensively",
                            Responsibilities = "Conduct preventive and corrective maintenance on turbine units||Monitor power output, vibration, and operational parameters||Replace worn components and perform underwater inspections||Maintain spare parts inventory and service logs||Report site conditions and performance data to central operations",
                            Summary = "Perform routine maintenance, troubleshooting, and performance monitoring at SHKT project sites nationwide.",
                            Title = "O&M Technician — Field Operations"
                        },
                        new
                        {
                            Id = 6,
                            Department = "business",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Keywords = "business development sales bde renewable energy hydropower clients",
                            Location = "New Delhi / Remote",
                            PostedDate = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "MBA or B.Tech with 4+ years in B2B sales or business development||Experience in energy, infrastructure, or industrial sectors||Strong network in state energy departments and utility companies||Excellent presentation, negotiation, and CRM skills||Willingness to travel domestically and internationally",
                            Responsibilities = "Identify and pursue new business opportunities in hydro and renewable energy||Build relationships with state DISCOMs, PSUs, IPPs, and industrial clients||Prepare proposals, feasibility presentations, and commercial bids||Represent MACLEC at industry conferences, trade shows, and government forums||Collaborate with engineering to scope projects and validate site potential",
                            Summary = "Drive revenue growth by identifying new project opportunities, building client relationships, and closing deals across India and international markets.",
                            Title = "Business Development Manager"
                        },
                        new
                        {
                            Id = 7,
                            Department = "business",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Keywords = "grant funding proposal writer government mnre cea subsidy",
                            Location = "New Delhi / Roorkee",
                            PostedDate = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "Master's in Public Policy, Energy, or related field with 3+ years experience||Deep understanding of India's renewable energy policy landscape||Proven track record of securing government grants or subsidies||Exceptional technical writing and stakeholder management skills||Network within MNRE, CEA, NITI Aayog, or state nodal agencies",
                            Responsibilities = "Identify and apply for government grants, subsidies, and R&D funding||Maintain relationships with MNRE, CEA, DSIR, and state energy departments||Draft policy briefs, white papers, and regulatory submissions||Track policy changes and advise leadership on strategic positioning||Support certification, compliance, and recognition processes",
                            Summary = "Secure government funding, subsidies, and policy support by navigating MNRE, CEA, DSIR, and state nodal agency frameworks.",
                            Title = "Government Relations & Grants Specialist"
                        },
                        new
                        {
                            Id = 8,
                            Department = "research",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Keywords = "research scientist hydrodynamics cfd materials corrosion renewable",
                            Location = "Roorkee, Uttarakhand",
                            PostedDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "Ph.D. in Fluid Mechanics, Ocean Engineering, or related field||Expertise in CFD (OpenFOAM, ANSYS Fluent, Star-CCM+)||Publication record in hydrodynamics or renewable energy journals||Experience with experimental hydraulics and flow measurement||Passion for translating research into commercial technology",
                            Responsibilities = "Conduct CFD and experimental studies on turbine hydrodynamic performance||Research wake recovery, array interaction, and channel blockage effects||Develop predictive models for power output under varying flow conditions||Publish findings in peer-reviewed journals and present at conferences||Collaborate with IIT Roorkee and international research partners",
                            Summary = "Lead fundamental and applied research on hydrokinetic turbine performance, wake dynamics, and aquatic environmental interaction.",
                            Title = "Research Scientist — Hydrodynamics"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
